language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t arkarmintun/fibonacci-complex-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arkarmintun/fibonacci-complex-client npm run test

after_success:
  - docker build -t arkarmintun/fibonacci-client ./client
  - docker build -t arkarmintun/fibonacci-nginx ./nginx
  - docker build -t arkarmintun/fibonacci-server ./server
  - docker build -t arkarmintun/fibonacci-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push arkarmintun/fibonacci-client
  - docker push arkarmintun/fibonacci-nginx
  - docker push arkarmintun/fibonacci-server
  - docker push arkarmintun/fibonacci-worker
